version: '1'
services: 
  api-app:
    restart: always
    build: ./dart_backend
    ports:
      - "7777:7777"
    depends_on:
      - postgres 
    environment: 
      - PORT=7777
      - DB_HOST=postgres  
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dart_backend
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    restart: always
    image: adminer
    ports: 
    - 9999:8080

volumes:
  db_data: {}
      